"""
audit_route_types.py — Route type counts for village-originating journeys.

Reads from outputs/data/journeys_all.csv (generated by run_full_pipeline.py).
Run from the project root:
    python3 scripts/audit_route_types.py
"""

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT  = ROOT / "outputs" / "data"

_ANMC_PATTERN = r"(?i)anmc|alaska.?native.?medical"


def _is_anmc(dest: object) -> bool:
    if pd.isna(dest):
        return False
    return bool(pd.Series([str(dest)]).str.contains(_ANMC_PATTERN, regex=True).iloc[0])


def _fmt(n: int, total: int) -> str:
    return f"{n:>4}  ({100 * n / total:4.1f}%)"


def main() -> None:
    ja_path = OUT / "journeys_all.csv"
    if not ja_path.exists():
        raise FileNotFoundError(
            f"journeys_all.csv not found at {ja_path}\n"
            "Run: python3 scripts/run_full_pipeline.py"
        )

    ja = pd.read_csv(ja_path)

    # Village-originating only
    village = ja[ja["village_name"].notna() & (ja["village_name"].str.strip() != "")].copy()
    n_total = len(village)

    # ── Classify each journey ────────────────────────────────────────────────
    is_primary    = village["route_type"].str.contains("Primary",   case=False, na=False)
    is_secondary  = village["route_type"].str.contains("Secondary", case=False, na=False)
    is_direct_ter = village["route_type"].str.contains("tertiary",  case=False, na=False)

    # Secondary: destination determined by medevac2_to (first leg lands at MHC)
    village["_sec_anmc"] = is_secondary & village["medevac2_to"].map(_is_anmc)
    village["_sec_out"]  = is_secondary & ~village["medevac2_to"].map(_is_anmc)
    sec_anmc = village[village["_sec_anmc"]]
    sec_out  = village[village["_sec_out"]]

    # Direct tertiary: destination is medevac1_to (bypasses MHC entirely)
    village["_dt_anmc"] = is_direct_ter & village["medevac1_to"].map(_is_anmc)
    village["_dt_out"]  = is_direct_ter & ~village["medevac1_to"].map(_is_anmc)
    dt_anmc = village[village["_dt_anmc"]]
    dt_out  = village[village["_dt_out"]]

    groups = [
        ("Village → MHC (primary only)",      village[is_primary]),
        ("Village → MHC → ANMC (secondary)",  sec_anmc),
        ("Village → MHC → outside (secondary)", sec_out),
        ("Village → ANMC (direct tertiary)",   dt_anmc),
        ("Village → outside (direct tertiary)", dt_out),
    ]

    other = village[~(is_primary | is_secondary | is_direct_ter)]

    # ── Print ────────────────────────────────────────────────────────────────
    print(f"\n{'='*62}")
    print(f"VILLAGE-ORIGINATING MEDEVAC ROUTES  (n = {n_total} journeys)")
    print(f"{'='*62}")
    print(f"{'Route':<42} {'Journeys':>9}  {'Patients':>8}")
    print(f"{'-'*62}")

    for label, subset in groups:
        j = len(subset)
        p = subset["MRN"].nunique()
        pct = f"{100 * j / n_total:.1f}%" if n_total else "—"
        print(f"  {label:<40} {j:>4} ({pct:>5})  {p:>8}")

    if len(other) > 0:
        j = len(other)
        p = other["MRN"].nunique()
        pct = f"{100 * j / n_total:.1f}%"
        print(f"  {'Unclassified':<40} {j:>4} ({pct:>5})  {p:>8}")

    print(f"{'-'*62}")
    print(f"  {'TOTAL':<40} {n_total:>4}          {village['MRN'].nunique():>8}")

    # ── Secondary destination detail ─────────────────────────────────────────
    if is_secondary.any():
        print(f"\n{'='*62}")
        print("SECONDARY TRANSFER DESTINATIONS  (medevac2_to)")
        print(f"{'='*62}")
        print(
            village[is_secondary]["medevac2_to"]
            .fillna("(missing)")
            .value_counts()
            .to_string()
        )

    # ── Direct tertiary destination detail ──────────────────────────────────
    if is_direct_ter.any():
        print(f"\n{'='*62}")
        print("DIRECT TERTIARY DESTINATIONS  (medevac1_to)")
        print(f"{'='*62}")
        print(
            village[is_direct_ter]["medevac1_to"]
            .fillna("(missing)")
            .value_counts()
            .to_string()
        )

    print(f"\n{'='*62}\n")


if __name__ == "__main__":
    main()
