"""
audit_route_types.py — Route type counts for village-originating journeys.

Reads from outputs/data/journeys_all.csv (generated by run_full_pipeline.py).
Run from the project root:
    python3 scripts/audit_route_types.py
"""

import pandas as pd
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT  = ROOT / "outputs" / "data"


def main() -> None:
    ja_path = OUT / "journeys_all.csv"
    if not ja_path.exists():
        raise FileNotFoundError(
            f"journeys_all.csv not found at {ja_path}\n"
            "Run: python3 scripts/run_full_pipeline.py"
        )

    ja = pd.read_csv(ja_path)

    # ── All records ──────────────────────────────────────────────────────────
    print(f"\n{'='*55}")
    print("ALL RECORDS IN DATABASE")
    print(f"{'='*55}")
    rt_all = ja["route_type"].value_counts(dropna=False)
    print(rt_all.to_string())
    print(f"\nTotal: {len(ja):,} journeys, {ja['MRN'].nunique():,} unique patients")

    # ── Village-originating only ─────────────────────────────────────────────
    village = ja[ja["village_name"].notna() & (ja["village_name"].str.strip() != "")].copy()

    print(f"\n{'='*55}")
    print("VILLAGE-ORIGINATING JOURNEYS")
    print(f"{'='*55}")

    route_map = {
        "Primary only (village → MHC)":        village["route_type"].str.contains("Primary",   case=False, na=False),
        "Secondary (village → MHC → outside)": village["route_type"].str.contains("Secondary", case=False, na=False),
        "Direct tertiary (village → outside)": village["route_type"].str.contains("tertiary",  case=False, na=False),
    }

    rows = []
    for label, mask in route_map.items():
        subset = village[mask]
        rows.append({
            "Route type":      label,
            "N journeys":      len(subset),
            "N unique patients": subset["MRN"].nunique(),
            "% of village":    f"{100 * len(subset) / len(village):.1f}%",
        })

    other = village[~(route_map["Primary only (village → MHC)"] |
                      route_map["Secondary (village → MHC → outside)"] |
                      route_map["Direct tertiary (village → outside)"])]
    if len(other) > 0:
        rows.append({
            "Route type":        "Other / unclassified",
            "N journeys":        len(other),
            "N unique patients": other["MRN"].nunique(),
            "% of village":      f"{100 * len(other) / len(village):.1f}%",
        })

    summary = pd.DataFrame(rows)
    print(summary.to_string(index=False))
    print(f"\nTotal village-originating: {len(village):,} journeys, {village['MRN'].nunique():,} unique patients")

    # ── MHC-presenting (excluded) ────────────────────────────────────────────
    mhc = ja[ja["village_name"].isna() | (ja["village_name"].str.strip() == "")]
    print(f"\n{'='*55}")
    print("MHC-PRESENTING (EXCLUDED FROM VILLAGE COHORT)")
    print(f"{'='*55}")
    print(f"N journeys:        {len(mhc):,}")
    print(f"N unique patients: {mhc['MRN'].nunique():,}")
    print("\nRoute type breakdown:")
    print(mhc["route_type"].value_counts(dropna=False).to_string())

    print(f"\n{'='*55}\n")


if __name__ == "__main__":
    main()
